-- Create tenants table if not exists
CREATE TABLE IF NOT EXISTS tenants (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  subdomain TEXT UNIQUE NOT NULL,
  primary_color TEXT DEFAULT '#3b82f6',
  secondary_color TEXT DEFAULT '#1e40af',
  logo_url TEXT,
  favicon_url TEXT,
  hero_image_url TEXT,
  contact_email TEXT,
  contact_phone TEXT,
  address TEXT,
  website TEXT,
  description TEXT,
  mayor TEXT,
  population INTEGER,
  area REAL,
  postal_code TEXT,
  latitude REAL,
  longitude REAL,
  timezone TEXT DEFAULT 'Europe/Berlin',
  locale TEXT DEFAULT 'de-DE',
  currency TEXT DEFAULT 'EUR',
  features JSONB,
  opening_hours JSONB,
  social_media JSONB,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- Insert Horn-Bad Meinberg tenant if not exists
INSERT INTO tenants (
  id, name, subdomain, primary_color, secondary_color,
  logo_url, favicon_url, hero_image_url,
  contact_email, contact_phone, address, website,
  description, mayor, population, area, postal_code,
  latitude, longitude, timezone, locale, currency,
  features, opening_hours, social_media,
  created_at, updated_at
) VALUES (
  'hornbadmeinberg',
  'Horn-Bad Meinberg',
  'hornbadmeinberg',
  '#4A7C7E',
  '#2C5456',
  '/assets/hornbadmeinberg/logo.jpg',
  '/assets/hornbadmeinberg/favicon.jpg',
  '/assets/hornbadmeinberg/hero.png',
  'info@horn-badmeinberg.de',
  '+49 5234 9710',
  'Mittelstraße 16, 32805 Horn-Bad Meinberg',
  'https://www.horn-badmeinberg.de',
  'Staatlich anerkannter Heilbadeort im Kreis Lippe',
  'Michael Ruttner',
  17000,
  120.5,
  '32805',
  51.8833,
  8.9667,
  'Europe/Berlin',
  'de-DE',
  'EUR',
  '{"news":true,"events":true,"waste":true,"chat":true,"forms":true,"clubs":true,"education":true,"attractions":true}'::jsonb,
  '{"Montag":"08:00-12:00, 14:00-16:00","Dienstag":"08:00-12:00, 14:00-18:00","Mittwoch":"08:00-12:00","Donnerstag":"08:00-12:00, 14:00-16:00","Freitag":"08:00-12:00"}'::jsonb,
  '{"facebook":"https://www.facebook.com/HornBadMeinberg","instagram":"https://www.instagram.com/hornbadmeinberg"}'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT (id) DO NOTHING;
